-- EcoCollect AI
-- Migration V1 : schéma initial PostgreSQL

CREATE TABLE municipalities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    name VARCHAR(150) NOT NULL,
    region VARCHAR(150),
    updated_at TIMESTAMP(6) NOT NULL,

    CONSTRAINT uk_municipality_code UNIQUE (code)
);

CREATE TABLE sectors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    description VARCHAR(500),
    name VARCHAR(150) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    municipality_id BIGINT NOT NULL,

    CONSTRAINT uk_sector_code_municipality
        UNIQUE (code, municipality_id),

    CONSTRAINT fk_sector_municipality
        FOREIGN KEY (municipality_id)
        REFERENCES municipalities(id)
);

CREATE TABLE containers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address VARCHAR(255) NOT NULL,
    capacity INTEGER NOT NULL,
    code VARCHAR(50) NOT NULL,
    container_type VARCHAR(30) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    status VARCHAR(30) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    sector_id BIGINT NOT NULL,

    CONSTRAINT uk_container_code UNIQUE (code),

    CONSTRAINT containers_container_type_check
        CHECK (
            container_type IN (
                'GENERAL_WASTE',
                'RECYCLING',
                'ORGANIC',
                'GLASS',
                'OTHER'
            )
        ),

    CONSTRAINT containers_status_check
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE',
                'MAINTENANCE',
                'FULL',
                'DAMAGED'
            )
        ),

    CONSTRAINT fk_container_sector
        FOREIGN KEY (sector_id)
        REFERENCES sectors(id)
);

CREATE TABLE collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_date TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    notes VARCHAR(1000),
    operator VARCHAR(150),
    status VARCHAR(30) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    weight_kg DOUBLE PRECISION,
    container_id BIGINT NOT NULL,

    CONSTRAINT collections_status_check
        CHECK (
            status IN (
                'SCHEDULED',
                'IN_PROGRESS',
                'COMPLETED',
                'CANCELLED',
                'FAILED'
            )
        ),

    CONSTRAINT fk_collection_container
        FOREIGN KEY (container_id)
        REFERENCES containers(id)
);

CREATE TABLE anomalies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    reported_at TIMESTAMP(6) NOT NULL,
    resolved_at TIMESTAMP(6),
    severity VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    type VARCHAR(40) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    container_id BIGINT NOT NULL,

    CONSTRAINT anomalies_severity_check
        CHECK (
            severity IN (
                'LOW',
                'MEDIUM',
                'HIGH',
                'CRITICAL'
            )
        ),

    CONSTRAINT anomalies_status_check
        CHECK (
            status IN (
                'REPORTED',
                'IN_PROGRESS',
                'RESOLVED',
                'CLOSED'
            )
        ),

    CONSTRAINT anomalies_type_check
        CHECK (
            type IN (
                'OVERFLOW',
                'DAMAGED',
                'ACCESS_BLOCKED',
                'ILLEGAL_DUMPING',
                'SENSOR_FAILURE',
                'OTHER'
            )
        ),

    CONSTRAINT fk_anomaly_container
        FOREIGN KEY (container_id)
        REFERENCES containers(id)
);
